version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    volumes:
      - ./src/:/app
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 60s
      timeout: 5s
      retries: 1
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: web
    ports:
      - 8081:80
    volumes:
      - ./src/:/app
    depends_on:
      - app
