name: Laravel

on:
  pull_request:
    branches: [ "main", "feature/**" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        docker-compose up -d
        docker-compose exec -T app cp .env.example .env
        docker-compose exec -T app cat .env
        docker-compose exec -T app composer install
        docker-compose exec -T app php artisan key:generate
    - name: Set up database
      run: |
        docker-compose exec -T app php artisan migrate --force
        docker-compose exec -T app php artisan db:seed --force
    - name: Run tests
      run: |
        docker-compose exec -T app php artisan test

