name: Laravel

on:
  pull_request:
    branches: [ "main", "feature/**" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        docker-compose up -d
        CONTAINER_ID=$(docker-compose ps -q app)
        docker exec $CONTAINER_ID cp .env.example .env
        docker exec $CONTAINER_ID cat .env
        docker exec $CONTAINER_ID composer install
        docker exec $CONTAINER_ID php artisan key:generate
    - name: Set up database
      run: |
        CONTAINER_ID=$(docker-compose ps -q app)
        docker exec $CONTAINER_ID php artisan migrate --force
        docker exec $CONTAINER_ID php artisan db:seed --force
    - name: Run tests
      run: |
        CONTAINER_ID=$(docker-compose ps -q app)
        docker exec $CONTAINER_ID php artisan test