name: Laravel

on:
  pull_request:
    branches: [ "main", "feature/**" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: database
      DB_USERNAME: root
      DB_PASSWORD: password

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        docker-compose up -d
        docker-compose exec -T app composer install
        docker-compose exec -T app cp .env.example .env
    - name: Set up database
      run: |
        docker-compose exec -T app php artisan migrate --force
        docker-compose exec -T app php artisan db:seed --force
    - name: Run tests
      run: |
        docker-compose exec -T app php artisan test

